// Generated by CoffeeScript 1.7.1
#target "aftereffects-12.0";
#include "../lib/core/_esy.js";
#include "../lib/core/_color.js";
#include "../lib/core/_file.js";
#include "../lib/core/_http.js";
#include "../lib/core/_ui.js";
var esy;

esy = new Esy();

esy.container = this;

esy.initialize();
