// Generated by CoffeeScript 1.10.0
var EsyColor;

EsyColor = (function() {
  function EsyColor() {}

  EsyColor.prototype.hexToRgb = function(hex) {
    var b, g, r;
    hex = parseInt(hex, 16);
    r = hex >> 16;
    g = (hex & 0x00ff00) >> 8;
    b = hex & 0xff;
    return [r, g, b];
  };

  EsyColor.prototype.rgbToHex = function(rgb) {
    var componentToHex;
    componentToHex = function(c) {
      var hex;
      hex = c.toString(16);
      if (hex.length === 1) {
        return "0" + hex;
      } else {
        return hex;
      }
    };
    return componentToHex(rgb[0] * 255) + componentToHex(rgb[1] * 255) + componentToHex(rgb[2] * 255);
  };

  EsyColor.prototype.hexToHsl = function(hex) {
    var b, g, r;
    hex = parseInt(hex, 16);
    r = hex >> 16;
    g = (hex & 0x00ff00) >> 8;
    b = hex & 0xff;
    return [r / 255, g / 255, b / 255];
  };

  return EsyColor;

})();
