// Generated by CoffeeScript 1.7.1
var EsyColor;

EsyColor = (function() {
  function EsyColor() {}

  EsyColor.prototype.hexToRgb = function(hex) {
    var b, g, r;
    hex = parseInt(hex, 16);
    r = hex >> 16;
    g = (hex & 0x00ff00) >> 8;
    b = hex & 0xff;
    return [r, g, b];
  };

  EsyColor.prototype.hexToHsl = function(hex) {
    var b, g, r;
    hex = parseInt(hex, 16);
    r = hex >> 16;
    g = (hex & 0x00ff00) >> 8;
    return b = hex & 0xff;
  };

  return EsyColor;

})();
