// Generated by CoffeeScript 1.7.1
Esy.color = (function() {
  function color() {}

  color.prototype.hexToRgb = function(hex) {
    var b, g, r;
    hex = parseInt(hex, 16);
    r = hex >> 16;
    g = (hex & 0x00ff00) >> 8;
    b = hex & 0xff;
    return [r, g, b];
  };

  color.prototype.hexToHsl = function(hex) {
    var b, g, r;
    hex = parseInt(hex, 16);
    r = hex >> 16;
    g = (hex & 0x00ff00) >> 8;
    return b = hex & 0xff;
  };

  return color;

})();
