// Generated by CoffeeScript 1.10.0
var EsyComposition;

EsyComposition = (function() {
  function EsyComposition() {}

  EsyComposition.prototype.hasLayers = function(composition) {
    return composition.numLayers > 0;
  };

  EsyComposition.prototype.find = function(composition, layerName) {
    var i, j, ref;
    if (composition) {
      if (this.hasLayers(composition)) {
        for (i = j = 1, ref = composition.numLayers; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
          if (composition.layers[i].name === layerName) {
            return composition.layers[i];
          }
        }
      }
    } else {
      return alert("Cannot find composition " + composition);
    }
  };

  return EsyComposition;

})();
