// Generated by CoffeeScript 1.7.1
var EsyFile;

EsyFile = (function() {
  function EsyFile() {}

  EsyFile.prototype["delete"] = function(filepath) {
    var file;
    file = File(filepath);
    return file.remove();
  };

  EsyFile.prototype.append = function(filepath, content) {
    var file;
    file = File(filepath);
    file.open("a");
    file.write(content);
    file.close();
    return file;
  };

  EsyFile.prototype.buildExtendScript = function(filepath, destinations) {
    var content, destination, read, _i, _len, _results;
    content = this.read(filepath);
    content = content.replace("esy.debug = true", "esy.debug = false");
    read = (function(_this) {
      return function(str, p1) {
        return _this.read("" + (_this.path(filepath)) + "/" + p1);
      };
    })(this);
    content = content.replace(/#include \"(.*)\";/g, read);
    if (typeof destinations === "string") {
      destinations = [destinations];
    }
    _results = [];
    for (_i = 0, _len = destinations.length; _i < _len; _i++) {
      destination = destinations[_i];
      _results.push(this.create("" + (destination.toString()), content));
    }
    return _results;
  };

  EsyFile.prototype.create = function(filepath, content, overwrite) {
    var file;
    if (content == null) {
      content = "";
    }
    if (overwrite == null) {
      overwrite = true;
    }
    if (overwrite) {
      this["delete"](filepath);
    }
    file = File(filepath);
    file.open("w");
    file.write(content);
    file.close();
    return file;
  };

  EsyFile.prototype.exists = function(filepath) {
    var file;
    file = File(filepath);
    if (file.created) {
      return file;
    } else {
      return false;
    }
  };

  EsyFile.prototype.read = function(filepath) {
    var content, file;
    file = File(filepath);
    file.open("r");
    content = file.read();
    file.close();
    return content;
  };

  EsyFile.prototype.folderName = function(filepath) {
    var folderName;
    folderName = this.filename(filepath);
    return folderName;
  };

  EsyFile.prototype.filename = function(filepath) {
    var filename;
    filename = filepath.substr(filepath.lastIndexOf('/') + 1);
    return filename;
  };

  EsyFile.prototype.path = function(filepath) {
    var filename;
    filename = filepath.substr(0, filepath.lastIndexOf('/'));
    return filename;
  };

  return EsyFile;

})();
