// Generated by CoffeeScript 1.10.0
var EsyProject;

EsyProject = (function() {
  function EsyProject() {}

  EsyProject.prototype.hasItems = function() {
    return app.project.numItems > 0;
  };

  EsyProject.prototype.first = function(itemName) {
    var compositions;
    compositions = this.find(itemName);
    return compositions[0];
  };

  EsyProject.prototype.find = function(itemName) {
    var compositions, i, item, j, ref;
    if (this.hasItems) {
      compositions = [];
      for (i = j = 1, ref = app.project.numItems; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        if (app.project.item(i).name === itemName) {
          item = app.project.item(i);
          if (item instanceof CompItem) {
            compositions.push(item);
          }
        }
      }
    }
    return compositions;
  };

  EsyProject.prototype.filter = function(expression, type) {
    var i, item, items, j, passes, ref;
    items = [];
    if (this.hasItems) {
      for (i = j = 1, ref = app.project.numItems; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        item = app.project.item(i);
        passes = true;
        if (expression) {
          if (!expression.test(item.name)) {
            passes = false;
          }
        }
        if (type) {
          if (item.typeName !== type) {
            passes = false;
          }
        }
        if (passes) {
          items.push(item);
        }
      }
    }
    return items;
  };

  return EsyProject;

})();
