// Generated by CoffeeScript 1.7.1
var EsyProject;

EsyProject = (function() {
  function EsyProject() {}

  EsyProject.prototype.hasItems = function() {
    return app.project.numItems > 0;
  };

  EsyProject.prototype.find = function(itemName) {
    var i, _i, _ref;
    if (this.hasItems) {
      for (i = _i = 1, _ref = app.project.numItems; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        if (app.project.item(i).name === itemName) {
          return app.project.item(i);
        }
      }
    }
  };

  EsyProject.prototype.filter = function(expression, type) {
    var i, item, items, passes, _i, _ref;
    if (this.hasItems) {
      items = [];
      for (i = _i = 1, _ref = app.project.numItems; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        item = app.project.item(i);
        passes = true;
        if (expression) {
          if (!expression.test(item.name)) {
            passes = false;
          }
        }
        if (type) {
          if (item.typeName !== type) {
            passes = false;
          }
        }
        if (passes) {
          items.push(item);
        }
      }
      return items;
    }
  };

  return EsyProject;

})();
