// Generated by CoffeeScript 1.10.0
var EsyUpdater;

EsyUpdater = (function() {
  function EsyUpdater(opts) {
    this.repo = opts.repo, this.file = opts.file, this.destination = opts.destination;
    this.localVersion = opts.version;
    this.username = encodeURIComponent(system.userName);
    this.data;
    this.remoteVersion;
    this.connection;
  }

  EsyUpdater.prototype.initialize = function() {};

  EsyUpdater.prototype.makeConnection = function() {};

  EsyUpdater.prototype.getLatestVersion = function() {};

  EsyUpdater.prototype.checkIfLatest = function() {};

  EsyUpdater.prototype.checkForUpdate = function() {};

  EsyUpdater.prototype.update = function() {};

  return EsyUpdater;

})();
