// Generated by CoffeeScript 1.7.1
var EsyUpdater;

EsyUpdater = (function() {
  function EsyUpdater(opts) {
    this.repo = opts.repo, this.file = opts.file, this.destination = opts.destination;
    this.localVersion = opts.version;
    this.username = encodeURIComponent(system.userName);
    this.data;
    this.remoteVersion;
  }

  EsyUpdater.prototype.initialize = function() {};

  EsyUpdater.prototype.getLatestVersion = function() {
    var data, url;
    url = encodeURIComponent("https://api.github.com/repos/" + this.repo + "/releases");
    data = eval(esy.http.get("http://hyle.dev/proxy?url=" + url + "&username=" + this.username));
    this.data = data[0];
    this.remoteVersion = this.data.tag_name;
    return this.remoteVersion;
  };

  EsyUpdater.prototype.checkIfLatest = function() {
    if (this.remoteVersion == null) {
      this.remoteVersion = this.getLatestVersion();
    }
    return this.remoteVersion === this.localVersion;
  };

  EsyUpdater.prototype.checkForUpdate = function() {
    if (!this.checkIfLatest()) {
      if (confirm("An update is available for " + this.repo + " (" + this.remoteVersion + "). Do you want to download the update?")) {
        return this.update();
      }
    } else {
      return true;
    }
  };

  EsyUpdater.prototype.update = function() {
    var content, url;
    url = encodeURIComponent("https://raw.githubusercontent.com/" + this.repo + "/master/" + this.file);
    content = esy.http.get("http://hyle.dev/proxy?url=" + url + "&username=" + this.username);
    esy.file.create("" + this.destination + "/esy_" + this.remoteVersion + ".jsx", content);
    log("delete " + this.destination + "/esy_" + this.localVersion + ".jsx");
    return esy.file["delete"]("" + this.destination + "/esy_" + this.localVersion + ".jsx");
  };

  return EsyUpdater;

})();
